#!/bin/sh
# init-mc
# Do first-time initialisation of the Keycloak instance used by MC
REALM=MC
CLIENT_ID=mc-ui

KCADM=/opt/jboss/keycloak/bin/kcadm.sh
${KCADM} config credentials --server http://localhost:8080/auth --realm master --user "${KEYCLOAK_USER}" --password "${KEYCLOAK_PASSWORD}"
${KCADM} create realms -s "realm=${REALM}" -s enabled=true
${KCADM} create clients -r "${REALM}" -s "clientId=${CLIENT_ID}" -s enabled=true
${KCADM} create users -r "${REALM}" -s "username=${KEYCLOAK_USER}" -s enabled=true